### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by raucao** [remotestorage/design#2]
Just FYI: I asked @jancborchardt on IRC about licensing of our design assets and he said his own things are CC-BY-SA 4.0 and that's what he recommends for new stuff as well.

**Comment by jancborchardt** [comment]
Ayyyup! :)

**Comment by michielbdejong** [comment]
It occurred to me this morning that maybe we should say a bit more about it, since the remoteStorage logo has a meaning that is sort of "owned" by the project. So the artwork would be CC-BY-SA 4.0, where the 'BY' refers to the actual artist (regardless of in which context or with which goal this artwork was created), but then maybe there is also something like "the brand", which I think should be owned by "the remoteStorage project".

That begs the question of how the project is organized and by who it is governed - what does it mean to say the project owns the brand? I think we can loosely define the remoteStorage project as the sum of the people who have contributed to it in the past. But in practice, we take decisions at the "core team meetings" we sometimes organize through the forum, so ultimately, the people who 1) have made some contributions to the project, and 2) show up for these core team meetings when they happen, would be the ones to vote about whether a certain use of the brand is good or bad, and also decide for instance what information we want to display on remotestorage.io, and how (the last core team meeting was mainly about the website contents iirc).

So shall we say the brand is owned by the remoteStorage project, whereas the artwork is attributed to the artist through CC-BY-SA? (reopening this issue)

**Comment by raucao** [comment]
If there's no trademark, then nobody owns the brand. Simple as that. ;)

**Comment by michielbdejong** [comment]
It's already a recognizable trade mark, even though we didn't bother registering it anywhere.

We can make up our own conditions of use when we publish something. We can say 'you may use this icon to refer to remoteStorage'. It's sort of implied anyway, so we might as well mention it in the readme of this repo.

**Comment by michielbdejong** [comment]
Also would help to avoid confusion when people don't understand how remoteStorage and 5apps relate to each other (people usually assume everything is commercial lock-in unless you mention otherwise)

**Comment by jancborchardt** [comment]
I think that’s not needed to be specified, is it? I did the logo for remoteStorage, and it should be used for this purpose only. The attribution to me is only because the copyright is bound to a person and that’s the simplest way to use the CC-BY-SA.

**Comment by raucao** [comment]
> We can make up our own conditions of use when we publish something. We can say 'you may use this icon to refer to remoteStorage'. It's sort of implied anyway, so we might as well mention it in the readme of this repo.

The question is: when would you disallow anyone from using it? And how would you enforce that? You only need trademarks and restrictions/statements, when you want to disallow something, otherwise everything goes.

> Also would help to avoid confusion when people don't understand how remoteStorage and 5apps relate to each other (people usually assume everything is commercial lock-in unless you mention otherwise)

That is a separate issue, and I don't see how adding "fake" trademark statements in a GitHub repo is going to help with that.

> I think that’s not needed to be specified, is it? I did the logo for remoteStorage, and it should be used for this purpose only. The attribution to me is only because the copyright is bound to a person and that’s the simplest way to use the CC-BY-SA.

It's all a bit difficult to specify really. The license doesn't restrict use cases, and also people using the widget shouldn't have to link your name in their app for doing so for example.

I think the only thing we can do (apart from actually registering a trademark if we want to protect the brand) is tell people to be excellent to each other, including us. And call them out in social media if they're misusing our stuff in an evil way.

**Comment by michielbdejong** [comment]
> I did the logo for remoteStorage, and it should be used for this purpose only.

Right, so that should be obvious enough for everybody to apply common sense.

Now it is also documented in this github issue, and we can refer back to this if there should ever be unclarity about it in the future.
